### PR TITLE
Amend Index sample to correct order of new Index method

### PR DESCRIPTION
**Pull request by dpen2000**
Checked this in released Preview 1 bits

### CODE REVIEW

**Comment by dpen2000** [comment]
@microsoft-github-policy-service agree

**Comment by dpen2000** [comment]
@microsoft-github-policy-service terminate

**Comment by dpen2000** [comment]
@microsoft-github-policy-service agree

**Comment by dpen2000** [comment]
Trying to ensure CLA is definitely signed as individual for me under this email address (old CLA agree may be rather old)

**Comment by jamesmontemagno** [comment]
@eiriktsarpalis to verify

**Comment by eiriktsarpalis** [comment]
Duplicate of https://github.com/dotnet/core/pull/9186? Strange that this doesn't show up as a merge conflict.

**Pull request closed without merging**
