### PR TITLE
Added notes about resolved ASP.NET Core issues

### PR DESCRIPTION
**Pull request by mkArtak**

### CODE REVIEW

**Comment by mkArtak** [comment]
@javiercn can you check the AAD-related known issues and advice, whether these also need to be marked as `resolved` in 5.0 ?

**Comment by mkArtakMSFT** [comment]
@leecow are you the right person to sign off on this or should I ping you someone else?

**Comment by rbhanda** [comment]
This has been added to https://github.com/dotnet/core-private/pull/75

**Comment by mkArtak** [comment]
@rbhanda  should this PR be closed then?

**Comment by rbhanda** [comment]
@mkArtak yes

**Pull request closed without merging**
