### PR TITLE
Update 1.0-1.1-api-diff_System.Runtime.CompilerServices.md to show ref returns

### PR DESCRIPTION
**Pull request by nietras**
Fix unsafe API changes that return a ref.

### CODE REVIEW

**Comment by Petermarcu** [comment]
@terrajobst , PTAL

**Comment by Petermarcu** [comment]
@terrajobst , can you take a look?

**Comment by Petermarcu** [comment]
@terrajobst , does this diff look correct?

**Comment by nietras** [comment]
@Petermarcu you can see this for yourself at:

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L242

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L234

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L277

Return is "!!T&", I assume this might be due to a tool, generating these diffs, that does not support ref returns.

**Comment by terrajobst** [comment]
The diff looks correct, although we need to fix our tools /cc @weshaggard. Otherwise, the next time we run an export `ref` returns will disappear again.

**Comment by weshaggard** [comment]
Agreed. I filed https://github.com/dotnet/buildtools/issues/1376 to track getting the tools to understand ref returns (PR's welcome :)).

**Comment by terrajobst** [comment]
> PR's welcome :)

Review welcome ;-)

https://github.com/dotnet/buildtools/pull/1377

**Pull request merged**
