### PR TITLE
add api diff between preview2 & preview3

### PR DESCRIPTION
**Pull request by Anipik**
cc @eiriktsarpalis @layomia @tarekgh @maryamariyan @michaelgsharp @safern @dotnet/ncl @buyaa-n @joperezr @krwq @steveharter @AaronRobinsonMSFT @jkoritzinsky @bartonjs @adamsitnik @carlossanlop @Jozkee 

@stephentoub @ericstj @danmoseley 

cc @pranavkm @Tratcher @Pilchie @davidfowl @dougbu @richlander

### CODE REVIEW

**Comment by tarekgh** [comment]
System.Diagnostics LGTM.

**Comment by AaronRobinsonMSFT** [comment]
System.Runtime.InteropServices LGTM.

**Review by safern — COMMENTED** [review]
System.Drawing LGTM

**Review by eiriktsarpalis — APPROVED** [review]
Linq and Collections LGTM

**Review by pranavkm — APPROVED** [review]
ASP.NET Core looks good. @halter73 could you do a once over?

**Review by karelz — APPROVED** [review]
System.Net LGTM

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
