### PR TITLE
Fix links in README.md

### PR DESCRIPTION
**Pull request by gbschenkel**
Created few more reference-style links, and fixed the path for the others.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/core?pullRequest=7558) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/core?pullRequest=7558) before we can accept your contribution.<br/><br/>:x: gbschenkel [sign now](https://cla.dotnetfoundation.org/dotnet/core?pullRequest=7558)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/core?pullRequest=7558) it.</sub>

**Comment by gbschenkel** [comment]
Well I just followed the "standard" used, if reference-style links is the problem, is only use the link directly instead.
The current README mostly links are broken, I just tried to fix them, and this is done with this modification.

From what I see, this README was created inside release-notes/ or is just a copy from there, I don't know if not better just right a abstract README with a link to the [Release Notes](release-notes/README.md) instead, and others stuffs.

**Comment by Eilon** [comment]
@gbschenkel yeah I'm hoping someone in this repo can help understand what the links should be. Maybe it's better to delete them and link to another file that has correct links, so things aren't as duplicated?

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
This fixes the links so that's better than before 😄 

/cc @richlander for thoughts on how the README should be structured.

**Pull request merged**
