### PR TITLE
Create sdk-implicit-refs.md

### PR DESCRIPTION
**Pull request by blackdwarf**
/cc @dsplaisted

### CODE REVIEW

**Comment by richlander** [comment]
Please avoid the word "glob". I think that this is a jargon word.

**Comment by blackdwarf** [comment]
@richlander a "glob" as a term that refers to a pattern that qualifies 0 or more items to be worked on is a pretty known term. It could be that it is jargon, but still it is something that people use.

**Comment by richlander** [comment]
We should put these files lower down than in the root. It's a bit odd, but I'd suggest the 1.0 folder. maybe 1.0/sdk  folder?

**Comment by blackdwarf** [comment]
@richlander changed the title. As agreed, let's merge this first and then I can move them around.

**Pull request merged**
