### PR TITLE
Api diff between 2.0 and 2.1

### PR DESCRIPTION
**Pull request by weshaggard**
@terrajobst @leecow @preetikr @richlander 

Here is the API diff between 2.0 and 2.1, let me know if you would like it in a different location.

### CODE REVIEW

**Comment by leecow** [comment]
Should probably live in release-notes/2.1 rather than Preview.

**Comment by weshaggard** [comment]
So you suggest I put it here `release-notes/2.1/api-diff/2.0-vs-2.1.md`

**Comment by leecow** [comment]
Hadn't thought of the api-diff directory but I like it.

**Comment by weshaggard** [comment]
Moved.

**Comment by terrajobst** [comment]
Looks good!

**Pull request merged**
