### PR TITLE
Remove VS for Mac properties from .NET 9 JSON fille

### PR DESCRIPTION
**Pull request by richlander**
I assume that removing VS for Mac information is correct. We should change our tools for this generating this file.

@leecow @rbhanda

### CODE REVIEW

**Comment by richlander** [comment]
Will this affect your use cases @mairaw?

**Comment by mairaw** [comment]
I'd need to test this to see if this is a required/optional field.

**Comment by richlander** [comment]
It would be good to remove use of it entirely from the website. There is no reason to display it.

**Comment by mairaw** [comment]
Yep, it makes sense with the retirement of the product. But other people consume this file, so it would be good to check other potential impacts. I can stop reading and displaying this info at the website for sure. Not sure if we have a schema file for this @leecow

**Comment by richlander** [comment]
Lee has an internal schema. I created a new one using .NET 9 APIs and my object model.

https://github.com/dotnet/core/pull/9427/files#diff-e735593946c18823b39b4ec6faf1c5936c357d36bec96dd04237cc1598e4797f

**Comment by richlander** [comment]
I'm closing this for now. However, it is still a topic to resolve.

**Pull request closed without merging**
