### PR TITLE
Added Fedora 24 binaries to the download table

### LINKED ISSUE #1032: Missing download for dotnet 1.1.4 for Fedora
Hello!
Shouldn't this [page][download-archive] have a link to download the SDK for Fedora 24?
There's info about the tar file in the [checksums][checksums], but there's no download link.

[download-archive]: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.4-download.md
[checksums]: https://dotnetcli.blob.core.windows.net/dotnet/checksums/1.1.4-sdk-sha.txt

### PR DESCRIPTION
**Pull request by johnnyasantoss**
Hello!
I've found the binaries for Fedora 24 and added them to the download archive of dotnet 1.1.4 LTS!
😄 

Fixes #1032

### CODE REVIEW

**Comment by Petermarcu** [comment]
@leecow can you review and merge if correct?

**Comment by omajid** [comment]
Fixed via https://github.com/dotnet/core/pull/1034 already?

**Comment by leecow** [comment]
Thank @johnnyasantoss but I already fixed up the dl page yesterday.

**Comment by johnnyasantoss** [comment]
Ok! I made this PR minutes after the issue, but I guess that I did not mention it.
Heheh

**Pull request closed without merging**
