### PR TITLE
5.0 install doc update

### PR DESCRIPTION
**Pull request by saudzgrte**
https://github.com/andy-portmen/native-client.git

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/core?pullRequest=7549) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/core?pullRequest=7549) before we can accept your contribution.<br/><br/>:x: saudzgrte [sign now](https://cla.dotnetfoundation.org/dotnet/core?pullRequest=7549)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/core?pullRequest=7549) it.</sub>

**Comment by mairaw** [comment]
Can you resolve the merge conflicts here? Also, preview 6 docs shouldn't be added at this time.

**Comment by mairaw** [comment]
Can you please take care of the merge conflicts here @saudzgrte?

**Review by axljoker03 — APPROVED** [review]

**Comment by leecow** [comment]
Linux install docs have bee rewritten and it looks like all of the issues in this PR were resolved.

**Pull request closed without merging**
