### PR TITLE
Incorrect version number for supported version

### PR DESCRIPTION
**Pull request by stevejgordon**
I believe this version should be the 2.1 LTS package?

### CODE REVIEW

**Comment by stevejgordon** [comment]
FYI @blowdart

**Comment by blowdart** [comment]
Yup, looks that way.

**Comment by rbhanda** [comment]
I thought the PR https://github.com/dotnet/core/pull/4137 took care of this issue

**Comment by leecow** [comment]
Looks like this has been resolved by another PR.

**Pull request closed without merging**
