### PR TITLE
Update no-response.yml - handling missing actions

### PR DESCRIPTION
**Pull request by Leslie-T-art**

### CODE REVIEW

**Comment by Leslie-T-art** [comment]
@dotnet-policy-service agree

**Comment by Leslie-T-art** [comment]
> @Leslie-T-art please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by Leslie-T-art** [comment]
@dotnet-policy-service agree

**Comment by mairaw** [comment]
What exactly are you trying to do here?

**Pull request closed without merging**
