### PR TITLE
Update link in Contributions section

### PR DESCRIPTION
**Pull request by CodeCharm**
Previous link went to 404

### CODE REVIEW

**Comment by svick** [comment]
As far as I can tell, https://github.com/dotnet/coreclr/pull/11944 intentionally removed that document, so I think that this link should be removed, not redirected to a branch that still has it.

cc: @richlander

**Comment by CodeCharm** [comment]
You're right; https://github.com/dotnet/coreclr/pull/11944/commits/9a94cd2b5c8fe5143633c4823330e9d1c09fdef8 shows the deliberate cleaning out of that. I'll remove the link entirely.

**Comment by karelz** [comment]
@richlander did you remove the doc on purpose, or was it just moved to core repo?

**Comment by richlander** [comment]
Ya, I deleted the file on purpose. It wasn't very useful any longer.

**Pull request merged**
