### PR TITLE
Replace old linker instructions with a pointer to the current ones

### PR DESCRIPTION
**Pull request by sbomer**

### CODE REVIEW

**Comment by sbomer** [comment]
@richlander PTAL

**Comment by sbomer** [comment]
@omajid good point, thanks - I've changed it to add a note while keeping the old instructions around. Does this look ok to you?

**Comment by omajid** [comment]
LGTM. Thanks!

I expect we will have to shortly update it again for 3.1. Is the linker still in preview for 3.1?

**Comment by sbomer** [comment]
Yup, and we haven't made any linker changes in 3.1.

**Comment by mairaw** [comment]
@richlander @leecow who owns the linker sample? Can you please review this PR? It's 5 months old.

**Comment by sbomer** [comment]
I'll just go ahead and merge now - I'm happy to make changes in a follow-up if there's feedback later.

**Pull request merged**
