### PR TITLE
Update Arm build host to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by richlander**
@janvorli @jkotas @wfurt

### CODE REVIEW

**Comment by omajid** [comment]
Does that mean .NET 7 on arm64 will no longer be supported on RHEL 8?

cc @tmds @leecow

**Comment by tmds** [comment]
Yes, RHEL 8 has glibc 2.28.

**Comment by richlander** [comment]
Is there a recommended pattern on how to do that?

Here are two examples:

- [Tensorflow](https://github.com/tensorflow/tensorflow/blob/f3963e82f21c9d094503568699877655f9dac508/tensorflow/tools/ci_build/devtoolset/build_devtoolset.sh#L48-L57) (use modern OS; download foreign old glibc to use at compile-time)
- [Python manylinux](https://github.com/pypa/manylinux/blob/main/README.rst#docker-images) (build in docker with old OS)

**Comment by richlander** [comment]
We're in the process of switching (for .NET 7+) of using Mariner as our build host. That likely means that we'll need to acquire a foreign glibc to compile with, much like the Tensorflow model, but in a consistent container image, like the Python manylinux model.

Context: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/615

**Review by IEvangelist — APPROVED** [review]

**Review by omajid — CHANGES_REQUESTED** [review]
As others have said, removing support for multiple OS's based on this quite recent glibc version is not desired.

**Pull request closed without merging**
