### PR TITLE
Update 2.2 known issues

### PR DESCRIPTION
**Pull request by jkotalik**

### CODE REVIEW

**Comment by vivmishra** [comment]
It is not clear why you are trying to delete this.

**Comment by jkotalik** [comment]
The issue with ANCM has already been resolved. We had a customer email us asking why ANCM hasn't been released on App Service and pointed to this. Now that the issue is resolved and isn't tied to a .NET release, why not remove it?

**Comment by omajid** [comment]
As an outsider to this project, a missing `known-issues`.md` sounds like someone neglected creating it. Perhaps the file can be kept around but modified to say that there are no know issues?

Also, some other existing documents (like https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-known-issues.md) link to it.

**Comment by leecow** [comment]
Thanks @jkotalik - What action does a customer impacted by this issue need to take? Install the January (or newer) hosting bundle? Change the AspNetCoreHostingModel setting back to InProcess? Both?

**Comment by jkotalik** [comment]
Just change the AspNetCoreHostingModel setting back to InProcess.

**Comment by leecow** [comment]
So I don't need to install an updated ANCM? That doesn't seem to make sense.

**Comment by jkotalik** [comment]
The reason this announcement was made was because ANCM wasn't deployed to Azure App Services when 2.2 released. Now that ANCM has been deployed to App Service, customers need to retarget their application to host InProcess. 

ANCM inside of the hosting bundle has been fine since the release of 2.2.0.

**Comment by leecow** [comment]
Gotcha, makes sense. I didn't read enough of the original issue to see the app services tie in.

**Pull request merged**
