### PR TITLE
1.0.0-api-list

### PR DESCRIPTION
**Pull request by leecow**

### CODE REVIEW

**Comment by leecow** [comment]
cc @ericstj , @terrajobst for the OK

**Comment by ericstj** [comment]
Are we sure GH can actually render this?  All the views I click on say it is too large.

**Comment by richlander** [comment]
That's an interesting problem.

One option is to break into two files:

- Standard Library
- Other .NET Core APIs

Would that help?

**Comment by leecow** [comment]
Working on an update that will use separate files per namespace and work better than the single giant file.

**Pull request closed without merging**
