### PR TITLE
Updating Support for Current releases from 15 to 18 months and adding Server 2012 to list of supported platforms 

### PR DESCRIPTION
**Pull request by jamshedd**

### CODE REVIEW

**Comment by wfurt** [comment]
btw is there a reason why Ubuntu16 is still supported? Debian bumped to 10 from 9+ in 5.0.

**Review by leecow — APPROVED** [review]
lgtm

**Comment by rbhanda** [comment]
This was merged by mistake. A new PR https://github.com/dotnet/core/pull/6458 is created

**Comment by richlander** [comment]
LGTM. Text is good. You can merge this/the other PR, in terms of my approval. Nice change!!

**Pull request merged**
