### PR TITLE
Added info for Ubuntu 17.10

### PR DESCRIPTION
**Pull request by yooakim**

### CODE REVIEW

**Comment by danmosemsft** [comment]
any reason for wget instead of curl as the other ones?

**Comment by richlander** [comment]
PTAL @leecow 

We should keep the command patterns the same unless there is a reason to do something different.

**Comment by yooakim** [comment]
@danmosemsft the reason is that later Ubuntu does not have CURL installed. So if we stick with CURL a note about installing CURL would be appropriate.

**Comment by leecow** [comment]
I've updated all downloads to use wget instead of curl to clear up some other inconsistencies.

**Pull request closed without merging**
