### PR TITLE
Fix broken .NET 9 dependencies link

### PR DESCRIPTION
**Pull request by MichaelSimons**
This is fallout from the changes made in https://github.com/dotnet/core/pull/9412.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@jongalloway, since you [enabled the MD linter](https://github.com/dotnet/core/pull/9444), is there an effort to proactively ensure all the markdown is valid in the repo so that contributions like this don't fail CI when they touch Markdown files that contain existing syntax issues?

**Comment by MichaelSimons** [comment]
@richlander, @mairaw - when the [markdown-link-check GH action was added](https://github.com/dotnet/core/pull/8346), is there a particular reason why the `check-modified-files-only` was turned on?  This is the reason this regression was not caught.  There can be other situation where changes outside the repo can cause a link break.  We should be catching those proactively IMO.

**Comment by jongalloway** [comment]
> @jongalloway, since you [enabled the MD linter](https://github.com/dotnet/core/pull/9444), is there an effort to proactively ensure all the markdown is valid in the repo so that contributions like this don't fail CI when they touch Markdown files that contain existing syntax issues?

Yes, @richlander asked me to set up markdown linting to ensure valid and quality markdown. I don't think we have link checking enabled, and don't know if that's a feature of the linter we're using.

**Comment by mairaw** [comment]
We do have link checking enabled with the markdown-link-check that I added a while back. But I think only I pay attention to those and now I know you do too @MichaelSimons. I probably added that setting so folks working on different files wouldn't get errors on changes that have nothing to do with their PR. But if you want to enable a full scan, you can change that setting. I cleaned up a lot of broken links on this repo over time, so hopefully it wouldn't be too bad to enable that now.

**Comment by MichaelSimons** [comment]
> Yes, @richlander asked me to set up markdown linting to ensure valid and quality markdown. I don't think we have link checking enabled, and don't know if that's a feature of the linter we're using.

I was only asking about the markdown linter.  There is already a [GH action that verifies the links](https://github.com/dotnet/core/blob/main/.github/workflows/markdown-link-check.yml).

The way the super linter is configured, it will only run on the modified code because of the `VALIDATE_ALL_CODEBASE: false` setting.  There is a potential for numerous syntax issues in the existing codebase.  My question is if anyone is going to proactively address those?  If not any contributor is going to have to fix them whenever they touch a file with pre-existing syntax issues

**Review by richlander — APPROVED** [review]

**Comment by mairaw** [comment]
And there will be many because I have local linter on my files and it's always complaining about linting issues on dotnet/core. I think as long as it's not enforced like the link check doesn't prevent you from merging even if it doesn't pass, it should be ok.

**Pull request merged**
