### PR TITLE
add f# info in README

### PR DESCRIPTION
**Pull request by enricosada**

### CODE REVIEW

**Comment by terrajobst** [comment]
Hey @enricosada! Thanks for adding that.

@cartermp and I just updated the roadmap to include more of the .NET components, which also includes F#. That's in PR #397. Does this work?

**Comment by enricosada** [comment]
@terrajobst awesome! can i also mention https://github.com/dotnet/netcorecli-fsc repo?

Because it's where f# sdk issue are posted. There is also source code for integration, [wiki](https://github.com/dotnet/netcorecli-fsc/wiki) for info about .net core versions, [example project per version](https://github.com/dotnet/netcorecli-fsc/tree/master/examples), etc

And there are the TODO issues :D 

I can add it with this pr if you want

**Comment by Petermarcu** [comment]
@terrajobst , thoughts on @enricosada 's question?

**Comment by terrajobst** [comment]
The README doesn't include dotnet/sdk. We should probably add both.

@enricosada, do you mind doing this?

**Pull request merged**
