### PR TITLE
Add Pete Gallagher Single Line Installs to Samples

### PR DESCRIPTION
**Pull request by pjgpetecodes**
I've added links to my posts around my single line install Scripts for .NET Core and .Net 5  for the Pi.

I've also added a link to my post for my single line setup script for remote Raspberry Pi Deploying and Debugging using VS Code.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Thanks for this addition in the documentation! That will clearly help some developers!

**Comment by pjgpetecodes** [comment]
> Thanks for this addition in the documentation! That will clearly help some developers!

Thanks @Ellerbach!

**Review by Ao-2 — COMMENTED** [review]
samples/RaspberryPiInstructions.md

**Comment by Ao-2** [comment]
https://github.com/dotnet/core/pull/6258#pullrequestreview-669004180

**Comment by Ao-2** [comment]
https://github.com/dotnet/core/pull/6258#pullrequestreview-669004180

**Comment by ManickaP** [comment]
@richlander Are we OK with linking personal blogs and or using URL shorteners?

**Review by skoal90 — APPROVED** [review]

**Review by skoal90 — APPROVED** [review]

**Comment by tango-charly** [comment]
@ManickaP 
I agree, I think the documentation should be available directly in the README of the GitHub project instead of a personal blog. 

The bat script will could definitely help ! But we could reconsider the manner to share and write the documentation !

**Review by ny030897 — APPROVED** [review]

**Comment by krwq** [comment]
cc @mairaw

**Comment by richlander** [comment]
Thanks for the contribution, Pete.

In general, I'm not a fan of the short links. For this particular case, it isn't a big deal. It's in a file I'd like to replace with content at dotnet/iot and eventually will. Also, the blog posts are about Windows Arm32, which we stopped supporting.

I'm merging this PR because it will be useful for some people now. It's a good reminder for me that I eventually need to cleanup this file.

**Comment by pjgpetecodes** [comment]
> Thanks for the contribution, Pete.
> 
> In general, I'm not a fan of the short links. For this particular case, it isn't a big deal. It's in a file I'd like to replace with content at dotnet/iot and eventually will. Also, the blog posts are about Windows Arm32, which we stopped supporting.
> 
> I'm merging this PR because it will be useful for some people now. It's a good reminder for me that I eventually need to cleanup this file.
> 
> 

Hey Rich...

Thanks very much indeed... Appreciate it! 

Curious about your comment re ARM32... 

> Also, the blog posts are about Windows Arm32, which we stopped supporting.

Not 100% sure what you mean? The posts are around Raspberry Pi OS / Debian... For sure this is all ARM32 however (I need to create a 64 bit version of this). 

Are you saying that ARM32 is no longer supported though?

I don't see that mentioned here...

https://www.github.com/dotnet/core/tree/main/release-notes%2F3.1%2F3.1-supported-os.md

https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md

Thanks!

**Comment by skoal90** [comment]
My apologies but been trying fix what this virus did to everything about have lost everything and I’m homeless and dealing with having to get new accounts 


Sent from Yahoo Mail for iPhone


On Monday, July 19, 2021, 7:06 PM, Rich Lander ***@***.***> wrote:




Thanks for the contribution, Pete.

In general, I'm not a fan of the short links. For this particular case, it isn't a big deal. It's in a file I'd like to replace with content at dotnet/iot and eventually will. Also, the blog posts are about Windows Arm32, which we stopped supporting.

I'm merging this PR because it will be useful for some people now. It's a good reminder for me that I eventually need to cleanup this file.

**Comment by skoal90** [comment]
Also you can look up the virus on dark web great examples of how the web destroyed my life


Sent from Yahoo Mail for iPhone


On Monday, July 19, 2021, 7:06 PM, Rich Lander ***@***.***> wrote:




Thanks for the contribution, Pete.

In general, I'm not a fan of the short links. For this particular case, it isn't a big deal. It's in a file I'd like to replace with content at dotnet/iot and eventually will. Also, the blog posts are about Windows Arm32, which we stopped supporting.

I'm merging this PR because it will be useful for some people now. It's a good reminder for me that I eventually need to cleanup this file.

**Pull request merged**
