### PR TITLE
Consistent output format

### PR DESCRIPTION
**Pull request by cincuranet**
Same format as the previous "blocks".

### CODE REVIEW

**Comment by cincuranet** [comment]
@richlander

**Comment by mairaw** [comment]
@richlander can you please review? This PR is two months old

**Comment by mairaw** [comment]
do you wanna resolve the merge conflicts here @cincuranet?

**Comment by richlander** [comment]
Thanks!

Fixed in https://github.com/dotnet/core/pull/5579. This PR as merge conflicts (due to your other changes) and I wanted to update it anyway.

**Comment by cincuranet** [comment]
OK. No problem.

**Pull request closed without merging**
