### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by meunice**

### CODE REVIEW

**Comment by leecow** [comment]
@meunice - can you tell us more about this idea? We already have documentation which is released for security updates and security information is included in release notes.

**Comment by omajid** [comment]
@leecow, from a quick google, I think it's about https://help.github.com/en/articles/adding-a-security-policy-to-your-repository

**Comment by leecow** [comment]
Thanks, Omair. I'll need to check with our security folks to see if they have thought about using this new-ish GitHub feature.

**Comment by leecow** [comment]
There are discussions going on about how to handle the security section across all .NET repos. No changes are likely in the near term.

**Pull request closed without merging**
