### PR TITLE
Update known-issues.md for the new msbuild logger

### PR DESCRIPTION
**Pull request by marcpopMSFT**
We accidentally shipping the new MSBuild logger with public classes in 17.5 previews and have since marked the classes internal.  While we don't believe anyone has started using these, we're recording it anyway as it would be a breaking change for them.

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@rbhanda this should have been merged for the 7.0.200 release a couple of weeks ago

**Review by rbhanda — APPROVED** [review]

**Comment by mairaw** [comment]
How can we force a CLA check? It seems stuck here.

**Comment by rbhanda** [comment]
No idea about the force CLA check so I created https://github.com/dotnet/core/pull/8282

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/pull/8282

**Pull request closed without merging**
