### PR TITLE
Acknowledge .NET Core 2.1 and Fedora 28 were released.

### PR DESCRIPTION
**Pull request by adelton**
Signed-off-by: Jan Pazdziora <jpazdziora@redhat.com>

### CODE REVIEW

**Comment by smudge202** [comment]
Does the [releases.csv](https://github.com/dotnet/core/blob/master/release-notes/releases.csv) need updating also? (I'm seeing this referenced to by Azure VSTS .Net Core Tool Installer Step)

**Comment by adelton** [comment]
Possibly yes, but I'm not really familiar with everything that might need to be changed with the new release, or indeed, where to find those download URLs. I was only looking from the point of view of Fedora releases, EOL'ed and current.

**Comment by smudge202** [comment]
Yeh, fair enough. Given that not everything seems to be working for 2.1.0 yet (see #1627 for example) it might be jumping the gun to merge this in just yet. 😞

**Comment by leecow** [comment]
The example in the document is just that, an example. Adding the link to the 2.1 supported OS versions makes sense. Maintaining a generic example doesn't feel like something that's needed.

**Pull request merged**
