### PR TITLE
Update dotnetsay tfm

### PR DESCRIPTION
**Pull request by wli3**
@richlander

### CODE REVIEW

**Comment by mairaw** [comment]
@wli3 should we update this to 3.1 now? Thanks

**Comment by wli3** [comment]
updated

**Comment by wli3** [comment]
@mairaw I don't have the access. Could you help me to merge it?

**Comment by mairaw** [comment]
@wli3 will do. Was just double checking with @richlander if he's ok with the two PRs for dotnetsay

**Comment by scottaddie** [comment]
@richlander or @KathleenDollard Please review and merge if it looks good. We've been using this tool in our ASP.NET Core-focused MS Learn modules, so it would be great to see a 3.1 version published to NuGet.

/cc: @nishanil @CamSoper

**Comment by richlander** [comment]
I think we should leave this as 2.1 and add roll-forward. That was always my intention but I never did it (obviously). I'll create a new PR.

**Comment by richlander** [comment]
Closed in favor of #5090. A new version has been uploaded to nuget.org.

**Pull request closed without merging**
