### PR TITLE
Fix description and broken links

### PR DESCRIPTION
**Pull request by AiOO**
I've found some typo and fixed it.

### CODE REVIEW

**Comment by Liudfdj** [comment]
Please leave a comment on my site if you’ve made a pie

**Comment by AiOO** [comment]
I'm sorry. I don't understand what you said.

**Comment by perlun** [comment]
@AiOO 

> I'm sorry. I don't understand what you said.

I think you're not the only one. 😆 Seems like a bot/troll comment to me.

**Comment by leecow** [comment]
Looks like this was already fixed.

**Pull request closed without merging**
