### PR TITLE
Fix root descriptor examples

### PR DESCRIPTION
**Pull request by sbomer**
The xml file should list assemblies without extensions.

### CODE REVIEW

**Comment by Petermarcu** [comment]
@sbomer

**Comment by sbomer** [comment]
@Petermarcu @richlander, what's the process here? May I go ahead and merge this?

**Comment by Petermarcu** [comment]
Yeah, if you like the change, go ahead.

**Comment by Petermarcu** [comment]
Ah, I didn't notice that you made the PR :)

**Pull request merged**
