### PR TITLE
Release artifacts for .NET Core 2.1.30

### PR DESCRIPTION
**Pull request by rbhanda**

### CODE REVIEW

**Comment by omajid** [comment]
Is it intentional that this gets rid of references to the 2.1.29 release?

**Comment by rbhanda** [comment]
Hello @omajid yes it is intentional

**Comment by omajid** [comment]
I see. Thanks for clarifying!

**Comment by omajid** [comment]
Actually, can you help me understand the reason? I can't remember release notes for any other release being removed. Is there something really that dangerous about 2.1.29 that it warrants the removal of all references to it?

**Pull request merged**
