### PR TITLE
Update support statements

### PR DESCRIPTION
**Pull request by Falco20019**
Follow-up for #9604

I removed iOS 15 and iPadOS 15 because they ended before .NET 9 was released (like @richlander did with Ubuntu 20.04). Feel free to instead add it to the `unsupported-versions` section if preferred.

Please check if the versions marked as supported are really already supported. I only updated the JSON now as discussion base based on what the currently available and non-EOL OS are.

* .NET 8
  * Moved from `supported-versions` to `unsupported-versions`
    * Alpine 3.17
    * Fedora 39
    * SUSE Enterprise Linux 12.5
    * iOS 15
    * iPadOS 15
* .NET 9
  * Removed from `supported-versions` since EOL before release
    * iOS 15
    * iPadOS 15
* ~~.NET 8 + .NET 9~~
  * ~~Added to `supported-versions`~~
    * ~~Fedora 41~~
    * ~~Windows Server 2025~~
    * ~~Windows Server Core 2025~~
    * ~~Nano Server 2025~~

/CC @richlander @sbomer @leecow

### CODE REVIEW

**Comment by richlander** [comment]
This looks good. Thanks!

I made this OS support tracking issue: https://github.com/dotnet/core/issues/9638. I'm waiting for the team to sign off on these new OSes. We can either wait for the team to sign off on them or remove them from this PR, merge the other changes now, and then make a follow-up PR with the new OSes later.

**Review by Moazzem-Hossain-pixel — APPROVED** [review]
Thanks

**Comment by richlander** [comment]
It would be great if you could remove the new OSes and we'll revisit that in January. I haven't been full sign off yet. There is no actual problem with the OSes, just the process.

**Review by Falco20019 — COMMENTED** [review]
Revert adding new OSes

**Comment by Falco20019** [comment]
@richlander Did as requested 👍

**Comment by richlander** [comment]
Thanks much!

**Review by richlander — APPROVED** [review]

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Need support

**Pull request merged**
