### PR TITLE
Update markdown formatting

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Comment by Falco20019** [comment]
There is a strange artifact in https://[raw.githubusercontent.com/dotnet/core/8a0d0c9577d9f6d864411e85b16e54d390eacc83/release-notes/7.0/supported-os.md](https://raw.githubusercontent.com/dotnet/core/8a0d0c9577d9f6d864411e85b16e54d390eacc83/release-notes/7.0/supported-os.md)

image

Looks a bit like there would be multi-threaded access on the writer?

**Comment by jamesmontemagno** [comment]
@richlander let me know if those linux links are okay 

https://developer.android.com/about/versions/pie is legit so we are fine to merge if the other updates I did are good

**Review by jamesmontemagno — APPROVED** [review]

**Comment by richlander** [comment]
I am going to make a couple more changes.

**Comment by Falco20019** [comment]
@richlander Shouldn‘t the links in the JSON be changed as well? As this is where those originated from.

**Comment by richlander** [comment]
Can you elaborate? I'm not following.

**Comment by richlander** [comment]
I understand now. I missed that @jamesmontemagno changed the markdown. I'll fix that in another one PR. Thanks for noticed that.

**Comment by Falco20019** [comment]
Yes, it seems that you reverted his changes by regenerating. He seemed to have fixed some links. And the Linux support would need to be fixed in the templates before regenerating.

**Comment by richlander** [comment]
The Apple links don't seem better to me. They don't relate to an OS version. What was your thinking on that @jamesmontemagno ?

**Comment by richlander** [comment]
https://github.com/dotnet/core/pull/9371

**Comment by jamesmontemagno** [comment]
> The Apple links don't seem better to me. They don't relate to an OS version. What was your thinking on that @jamesmontemagno ?

https://support.apple.com/ios/ goes to a random article on how to install it
https://support.apple.com/ipados doesn't exist
 
trying to align with the other ones for macos and apple-tv... there isn't a lifecycle though

**Pull request merged**
