### PR TITLE
Correcting typo

### PR DESCRIPTION
**Pull request by timheuer**
Minor nit, but my eyes couldn't unsee it.

### CODE REVIEW

**Comment by omajid** [comment]
IMO, this isn't a typo, but a difference in how quotes are used: https://en.wikipedia.org/wiki/Quotation_marks_in_English

**Comment by timheuer** [comment]
> IMO, this isn't a typo, but a difference in how quotes are used: https://en.wikipedia.org/wiki/Quotation_marks_in_English. Developer, in particular, prefer this style to avoid mistakes: http://www.catb.org/jargon/html/writing-style.html

Not a hill I'd climb to argue, but this isn't code (per the catb article which I could appreciate), it is a written explanation in English and the style guides would say this is incorrect.
- https://www.thepunctuationguide.com/quotation-marks.html
- https://writeshop.com/how-to-use-quotation-marks/

But again, I'm not going to battle the hill, just tell my English teacher on the side ;-)

**Comment by timheuer** [comment]
> IMO, this isn't a typo, but a difference in how quotes are used: https://en.wikipedia.org/wiki/Quotation_marks_in_English. Developer, in particular, prefer this style to avoid mistakes: http://www.catb.org/jargon/html/writing-style.html

Not a hill I'd climb to argue, but this isn't code (per the catb article which I could appreciate), it is a written explanation in English and the style guides would say this is incorrect.
- https://www.thepunctuationguide.com/quotation-marks.html
- https://writeshop.com/how-to-use-quotation-marks/

But again, I'm not going to battle the hill

**Comment by bartonjs** [comment]
I agree with Omair... "dev-quotes" are better here than American written dialogue quotes.

Apparently the British have decided that dev-quotes are the better form for dialogue.  I applaud them.  As both a reader, and an author, I hate the American way of moving terminal quotes to after the punctuation.

**Comment by rbhanda** [comment]
Alright, I will close the PR without merging it.

**Pull request closed without merging**
