### PR TITLE
add VS info for July 2.1 release

### PR DESCRIPTION
**Pull request by leecow**

### CODE REVIEW

**Comment by rbhanda** [comment]
Adding correct VS version info for 3.1 as well

**Comment by mairaw** [comment]
Is this for fixing the issue being discussed for https://dotnet.microsoft.com/download/visual-studio-sdks? Do you want me to test this on the dev environment?

**Comment by leecow** [comment]
I noticed these values missing while looking into that issue though I don't know if this will fix it as the previous 2.1 entry did have the correct version information.

**Comment by mairaw** [comment]
It seems it did. The page now shows VS versions for 2.1.

**Pull request merged**
