### PR TITLE
Reference latest package version from NuGet linker

### PR DESCRIPTION
**Pull request by nightblade9**
This way, you get the latest and greatest version, not a 2017 version.

### CODE REVIEW

**Comment by nightblade9** [comment]
@sbomer sorry for the delay. Is that better? I never noticed, but the line right above that mentions the same link that you posted, from which you can get the latest version. So, I added the latest version back in, with a hint ("as of writing") that might trigger future readers to look up the latest version.

Is this sufficient, or would you like something else?

**Comment by sbomer** [comment]
Perfect, thank you!

**Comment by karelz** [comment]
@sbomer is it ready for merge?

**Comment by sbomer** [comment]
Yup!

**Pull request merged**
