### PR TITLE
fix curl command for download deb package

### PR DESCRIPTION
**Pull request by namax**
fix curl command for download deb package in case installation in Ubuntu

### CODE REVIEW

**Comment by leecow** [comment]
Thanks @namax - all of the dl commands have been updated to use wget.

**Comment by namax** [comment]
hi @leecow 

thank you for the reply. I would like to help you guys,  if you have any "first time" issues just let me know.

**Comment by leecow** [comment]
Thanks, @namax ! You can see the updates in https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.5-download.md. Would you mind having a look before I prop them to the main website?

**Comment by namax** [comment]
Sure. What exactly do I need to do? Just review the text and the commands for typos?

**Comment by namax** [comment]
@leecow 
Eg this link is not found  - 

SDK Binaries  for windows 32 bit

https://download.microsoft.com/download/1/1/0/11046135-4207-40D3-A795-13ECEA741B32/dotnet-sdk-2.1.4-win-x86.zip

**Comment by leecow** [comment]
Thanks for the catch @namax.

Have a look at the [contributing](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md) doc for the best places to finds issues to coding issues to work on.

**Comment by namax** [comment]
Than you @leecow  I will read the document, but how I  should to propose  that I would like to work on some issue? Or I can just write in the comments? So I don't find out in the end of fixing some issue that somebody did earlier.  

I found another one 
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
Seems this is incorrect **-qO-**

**Comment by leecow** [comment]
Issues that no one is working on are marked "up for grabs". Commenting in the issue that you are working on it will be enough. 

With respect to wget -qO-, specifically the -O- portion; this saves the contents of the file to STDOUT which allows it to be directly piped to the gpg command.

**Pull request closed without merging**
