### PR TITLE
Create rc4-download.md

### PR DESCRIPTION
**Pull request by blackdwarf**
Added the page to unblock #541. The link points to the official pages for download to avoid people getting stuck on older versions of the CLI/SDK.

/cc @richlander

### CODE REVIEW

**Comment by richlander** [comment]
Should we point to the page that was intended? If they want RC4, then we should give RC4 (right?), which BTW isn't available from the site you linked to.

https://github.com/dotnet/core/blob/master/release-notes/download-archives/rc4-download.md

**Comment by blackdwarf** [comment]
@richlander I would like to avoid people installing RC4 when we released RTW. The main rationale would be that I would like to decrease potential user frustration when they run into issues that we actually solved in RTW.

**Comment by richlander** [comment]
You should validate that the VS 4 Mac folks are OK with that. 

In general, I agree. Good point. We should decide on our long-term plan here with the VS 4 Mac folks.

/cc @mhutch

**Comment by blackdwarf** [comment]
I already asked the VS 4 Mac folks on whether this would be OK which is why I made this change. 

I believe that the long-term plan should be that VS 4 Mac is tested against release versions of the Core SDK with the preference for stable version where/if possible. 

Thoughts?

**Pull request merged**
