### PR TITLE
supported-os: Update Fedora EOL versions.

### PR DESCRIPTION
**Pull request by RheaAyase**
Please notice that I went a month into the future so this update also marks F31 which **will be** EOL in a little over a month. I can split it into two PRs if that's preferred.

### CODE REVIEW

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/issues/5291
Fedora will reach end of life in November and we will update the supported OS during our November release.

**Comment by RheaAyase** [comment]
.NET 5 shouldn't go out with "Fedora 30+" in the list though.

**Comment by RheaAyase** [comment]
I removed the `31` EOL line then.

**Comment by mairaw** [comment]
@rbhanda the PR has been updated. Does this look good or anything else needs to be addressed?

**Review by rbhanda — APPROVED** [review]

**Pull request merged**
