### PR TITLE
.NET 7 end of support

### PR DESCRIPTION
**Pull request by karelz**
Move .NET 7 to end-of-life .NET versions.
Add link to 3.1 End of support announcement.

### CODE REVIEW

**Comment by mairaw** [comment]
you now have some conflicts because .NET 7 was already removed as part of the release this morning. 
https://github.com/dotnet/core/pull/9308

The 3.1 entry should come after .NET 5

**Comment by martincostello** [comment]
I just noticed the release notes JSON files haven't been updated to indicate the end of support either. These should both be `eol` now?

https://github.com/dotnet/core/blob/fac4a52b236e6e2f2e0f43681448bfa769389df6/release-notes/7.0/releases.json#L8

https://github.com/dotnet/core/blob/fac4a52b236e6e2f2e0f43681448bfa769389df6/release-notes/releases-index.json#L38

**Comment by mairaw** [comment]
Good catch @martincostello. I'll open a PR for those.

**Comment by karelz** [comment]
Updated, ready for re-review

**Pull request merged**
