### PR TITLE
Add the Project System

### PR DESCRIPTION
**Pull request by etbyrd**

### CODE REVIEW

**Comment by leecow** [comment]
While work in the project-system repo may effect .NET Core, I don't know that it belongs in this list. @karelz ?

**Comment by cartermp** [comment]
@leecow I think it belongs. It's the project system for .NET SDK-style projects.

**Comment by karelz** [comment]
Agreed cc @davkean

**Comment by davkean** [comment]
I would have make it "Language/Tooling" and include MSBuild too. Bugs are often moved between project-system/msbuild/sdk/cli.

**Pull request merged**
