### PR TITLE
Adding msbuild support to the samples

### PR DESCRIPTION
**Pull request by Petermarcu**
project.json and msbuild support can live together for these samples for now. We should delete the project.json's when the time is right.

### CODE REVIEW

**Comment by Petermarcu** [comment]
@richlander

**Comment by Petermarcu** [comment]
This is a fix to address this: https://github.com/dotnet/core/issues/363

**Comment by blackdwarf** [comment]
A question: do we want to actually start anew and show off the easier new csproj syntax for these samples? They are pretty basic, so it shouldn't be a problem. I can make that PR.

**Comment by Petermarcu** [comment]
Sure, let's merge this and then you can clean them up as a good example for people who migrate.

**Comment by blackdwarf** [comment]
LGTM then

**Pull request merged**
