### PR TITLE
Updating versions and support.

### PR DESCRIPTION
**Pull request by Petermarcu**

### CODE REVIEW

**Comment by Petermarcu** [comment]
@leecow, look good?

**Comment by leecow** [comment]
LGTM

**Comment by lemmaa** [comment]
@Petermarcu What does 'support' mean on this document? Does it mean customer service or partner service? If so, it would be better to remove the `[S]` tag from Ubuntu/arm32. We do our best to ensure that .NET Core will work properly on Ubuntu/arm32, but we have no plans to officially support Ubuntu/arm32 yet. For now, only Tizen is on that range. We will do our best to be part of the .NET community. :)

**Comment by Petermarcu** [comment]
@lemmaa, I just updated it to community based on that. Thanks!

**Comment by lemmaa** [comment]
@Petermarcu, Thanks!

**Pull request merged**
