### PR TITLE
Artifacts for 3.0 GA release

### PR DESCRIPTION
**Pull request by vivmishra**

### CODE REVIEW

**Comment by dasMulli** [comment]
I know that my making breaking changes to the CLI in 3.0 isn't very good to admit publicly, but any reason https://github.com/dotnet/cli/pull/9892 didn't make it into the contributors list? 😅

**Comment by jamshedd** [comment]
@vivmish, @leecow, can you please take a look?

**Comment by leecow** [comment]
@dasMulli - my cleaning script to remove MSFT folks is pretty aggressive so will have a look and get you added back to the list.

**Comment by dasMulli** [comment]
no stress, it's not an issue for me or anything, was just surprised.

**Comment by leecow** [comment]
Figured it out ... my starting commit sha wasn't far enough back. https://github.com/dotnet/core/pull/3460

**Comment by leecow** [comment]
Thanks, @NextTurn. Will look at dates again to see if I can resolve the issues they were previously giving me.

**Pull request merged**
